### ISSUE TITLE
HTML indexes for multiple registers

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#18]
The existing index page for links to built documents should be replaced with a HTML view of the resources, as they would appear if aggregated into another domain - such as the OGC Building Blocks

Open question: should this have option to show all dependencies?   Generally its probably useful to say "if i use this what else am i importing that i can reuse" 

and 

"i  should consider implications of having multiple alternative approaches in the same environment"

both of these require transparency - so i favour a view that allows easy showing of imports with a clear visual distinction

**Comment by avillar** [comment]
I think we should show a list of dependencies, linking to their corresponding Slate page (local if it's local, remote if it's imported).

**Comment by avillar** [comment]
And, of course, we could mark the remote ones too.

**Comment by rob-metalinkage** [comment]
Dependencies for each individual is needed.

But seeing a collection and understanding there are other collections is probably valuable.  We can maintain a register of known registers automatically using the register.ttl push to a KG, and link to that perhaps.

**Comment by avillar** [comment]
I had two options for that:
a) add a flag to the postprocess so that both local and remote bbs are published (register.json, slate, etc.)
b) create a different script that can merge several register.json together and generate a KG with all of them

Re:b, that was also something that I'd like to do for the bblocks-viewer (either display a single register.json, or pull several, including dependencies).
